[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]
dependencies = ["test"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]
dependencies = ["clippy"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.rebuild]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean", "format"]

[tasks.install]
command = "cargo"
args = ["install", "--path", "./"]
dependencies = ["build"]
